"use client";
import { useState } from "react";
import ScenarioCauseFlow from "./ScenarioCauseFlow";
import { Users, School, Wallet, Database } from "lucide-react";
import { schoolYear, type EnrollmentYear } from "@/lib/enrollment-types";
import type { Levers, Outcomes } from "@/lib/scenario-types";
const fmt=(n:number|null)=>n===null?"Unknown":n.toLocaleString("en-PH",{maximumFractionDigits:2});
export default function WhyThisHappens({observed,previous,to,from,levers,year,source}:{observed:EnrollmentYear;previous?:EnrollmentYear;to?:Outcomes;from?:Outcomes;levers:Levers;year:number;source:string}) {
  const [choice,setChoice]=useState("Enrollment");
  const options=[{label:"Enrollment",Icon:Users},{label:"Classrooms",Icon:School},{label:"Budget",Icon:Wallet},{label:"Coverage",Icon:Database}];
  const Icon=options.find(o=>o.label===choice)!.Icon;
  let value=fmt(to?.enrollment??observed.enrollment),summary="Observed enrollment is the sum of reported grade / track and sex counts.",factors=[`${source} · SY ${schoolYear(observed.year)}.`,`Male ${fmt(observed.male)} + female ${fmt(observed.female)} = ${fmt(observed.enrollment)} reported enrollments.`,`Blanks remain missing. A sum may be partial; changes are descriptive, not causal.`];
  if(choice==="Enrollment"&&to&&year>observed.year){summary="Enrollment follows the same explicit rate each scenario year.";factors=[`Observed starting value: ${fmt(observed.enrollment)} (SY ${schoolYear(observed.year)}).`,`round(${fmt(from?.enrollment??observed.enrollment)} × [1 + (${levers.enrollmentGrowth} + ${levers.progression} + ${levers.access}) / 100]) = ${fmt(to.enrollment)}.`,`Growth + net progression + access are assumed percentage-point contributions, not an inferred forecast.`]}
  if(choice==="Classrooms"){value=to?fmt(to.remainingGap):"Unknown";summary=to?"A classroom gap is calculated only from an assumed inventory.":"Enrollment files contain no classroom inventory.";factors=to?[`Required rooms = ceil(${fmt(to.enrollment)} / ${levers.pupilsPerRoom}) = ${fmt(to.requiredRooms)}. Ratio is an assumption.`,`Usable rooms = initial rooms − unusable rooms + funded new / expansion / annex rooms + eligible rehabilitation = ${fmt(to.availableRooms)}.`,`Remaining gap = max(0, required − usable) = ${fmt(to.remainingGap)}. This is not an actual gap.`,"Annex / new-school packages assess affordability only. Land, catchment, travel distance, staffing and approval are still required."]:["Supply a classroom inventory under Political / Policy to estimate a gap.","No actual congestion, capacity, construction cost or funding impact is inferred."]}
  if(choice==="Budget"){value=to?`₱${fmt(to.annualSpend)}M`:"Not observed";summary="Budget shares are explicit planning choices, not recommended allocations.";factors=to?[`Eligible budget this year = ₱${fmt(to.availableBudget)}M. Funding interval: ${levers.fundingCycle} year(s).`,`Reserve maintenance ₱${fmt(to.maintenance)}M, then equity ₱${fmt(to.equityReserve)}M. Equity is unassigned and remains unspent.`,"Per intervention: funded units = min(request, floor(remaining envelope × strategy share / assumed unit cost)). No redistribution between categories.",`Actual scenario spend = maintenance + funded units × costs. Unspent = ₱${fmt(to.unspent)}M; no carryover.`,`ICT adds ${levers.ictShare}% × ₱${levers.ictCost}M per new room to construction costs.`]:["No budget or unit costs exist in the supplied enrollment files.","All currency controls are illustrative millions of pesos."]}
  if(choice==="Coverage"){value=`${fmt(observed.reporting)} / ${fmt(observed.schools)}`;summary="Coverage measures the supplied file, not national completeness or statistical confidence.";factors=[`${fmt(observed.reporting)} school records have at least one numeric enrollment cell.`,`${fmt(observed.knownCells)} / ${fmt(observed.sourceCells)} source count cells are numeric. Blanks may mean not offered or not reported.`,`${fmt(observed.matched)} schools matched to the previous year in this same area / sector.`,previous?`School records changed from ${fmt(previous.schools)} to ${fmt(observed.schools)}. Region reassignment or reporting changes can affect totals.`:"No preceding year is available for this selection."]}
  return <section className="panel why-panel" aria-labelledby="why-title"><div className="panel-head why-head"><h2 id="why-title">Why This Happened</h2></div>{to&&from&&<ScenarioCauseFlow to={to} from={from} levers={levers} year={year} baseYear={observed.year}/>}<details className="why-calculations" open={to?undefined:true}><summary>Explore the calculation</summary><div className="why-feature steady"><div className="why-feature-icon"><Icon size={25}/></div><div className="why-feature-content"><span>{to?"Computed estimate":"Observed data"} · {schoolYear(year)}</span><h3>{choice}</h3><div className="why-values"><strong>{value}</strong></div></div></div><div className="why-story" aria-live="polite"><p>{summary}</p><ul>{factors.map(f=><li key={f}>{f}</li>)}</ul></div><div className="why-outcomes-label">Explore the calculation</div><div className="why-outcomes">{options.map(({label,Icon})=><button key={label} aria-pressed={choice===label} className={choice===label?"active":""} onClick={()=>setChoice(label)}><Icon size={17}/><span>{label}</span></button>)}</div></details><p className="why-note">Deterministic arithmetic. No ML prediction or causal inference.</p></section>;
}

